src: introduce simple hints on incorrect chain
 # nft list chain x y
 Error: No such file or directory; did you mean chain ‘y’ in table inet ‘x’?
 list chain x y
              ^

Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>