scanner: add helpers token
without it, you get:
 nft list ct helpers table filter
 Error: syntax error, unexpected string, expecting helper or helpers

Fixes: 14fd3ad720f6e ("src: prepare for future ct timeout policy support")
Signed-off-by: Florian Westphal <fw@strlen.de>