src: introduce simple hints on incorrect object
 # nft add counter x test
 # nft list counter x test
 Error: No such file or directory; did you mean obj ‘test’ in table ip ‘x’?
 list counter x text
                ^^^^

Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>