tests: check ifname use in concatenated sets
error was:
 nft create set inet filter keepalived_ranges4 { type inet_service . ifname \; }
 Error: Empty string is not allowed

This was fixed in
6b00b9537e181 ("evaluate: skip evaluation of datatype concatenations").

Signed-off-by: Florian Westphal <fw@strlen.de>