rule: Fix build failure in rule.c
Commit c8a0e8c90 added #include <linux/netfilter_bridge.h> but that header needs
the definition of IFNAMSIZ from <net/if.h>
Sample build failure:

  CC       evaluate.lo
In file included from ../include/linux/netfilter_bridge.h:10:0,
                 from rule.c:32:
/usr/include/linux/if_pppox.h:42:20: error: 'IFNAMSIZ' undeclared here (not in a function)
  char          dev[IFNAMSIZ];          /* Local device to use */
                    ^
Makefile:687: recipe for target 'rule.lo' failed

Signed-off-by: Duncan Roe <duncan_roe@optusnet.com.au>
Signed-off-by: Pablo Neira Ayuso <pablo@netfilter.org>