tests: ip6: fix 'missing payload' error
ERROR: line 2: did not find payload information for rule 'iifname "eth0" ct state established,new tcp dport vmap {22 : drop, 222 : drop } masquerade'

Signed-off-by: Florian Westphal <fw@strlen.de>